# This is a basic workflow to help you get started with Actions

name: Cross Platform Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ "main" ]
    inputs:
      ssh:
        description: 'ssh connection to actions'
        required: false
        default: 'false'

env:
  TZ: Asia/Shanghai
  ER6POUT: er6p-out
  RASPOUT: rasp3b-out
  RELEDIR: relxyzss


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "buildroot"
  buildroot:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-20.04" ]
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          submodules: true
      
      - name: where i am
        run: |
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /bin
          sudo chown $USER:$GROUPS /bin
          echo -e "workspcace->$GITHUB_WORKSPACE"
      
      - name: ssh to actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

####################Raspberry 3B##########################################Raspberry 3B########################
  raspberry3B:
    needs: buildroot
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-20.04" ]
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          submodules: true
      
      - name: where i am
        run: |
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          echo -e "workspcace->$GITHUB_WORKSPACE"

      - name: clone source code
        working-directory: /workdir
        env:
          REPO_URL: https://git.busybox.net/buildroot
          REPO_BRANCH: 2021.11
        run: |
          df -hT $PWD
          git config --global advice.detachedHead false
          git clone --recurse-submodules --branch $REPO_BRANCH $REPO_URL
          cd /workdir/buildroot
          git checkout $REPO_BRANCH
          git pull origin $REPO_BRANCH
          ln -sf /workdir/buildroot $GITHUB_WORKSPACE/buildroot
          sudo apt-get -qq install sed make binutils gcc g++ bash patch bzip2 perl tar cpio unzip rsync wget libncurses-dev 

      - name: ssh to actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      
      - name: build
        run: |
          cd $GITHUB_WORKSPACE/buildroot
          make O="$RASPOUT" raspberrypi3_defconfig
          [ -e $GITHUB_WORKSPACE/rasp.config ] && cp -f $GITHUB_WORKSPACE/rasp.config $GITHUB_WORKSPACE/buildroot/$RASPOUT/.config
          make O="$RASPOUT" shadowsocks-libev
          #make O="$RASPOUT" toolchain
      
      - name: tar files and folders
        id: tartt
        run: |
          df -hT $PWD
          cd $GITHUB_WORKSPACE/buildroot/$RASPOUT
          tar -cjvf /workdir/$RASPOUT.${{ matrix.os }}.tar.bz2 ./host/ ./target/usr/bin/ ./target/bin/
          echo "stat=okk" >> $GITHUB_OUTPUT

      - name: upload file & directory
        uses: actions/upload-artifact@v3
        if: steps.tartt.outputs.stat == 'okk'
        with:
          name: raspi3b-toolchain
          path: /workdir/${{ env.RASPOUT }}.${{ matrix.os }}.tar.bz2



####################er6P######################################er6P############################
  er6P:
    needs: buildroot
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-20.04" ]
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          submodules: true
      
      - name: where i am
        run: |
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      - name: clone source code
        working-directory: /workdir
        env:
          REPO_URL: https://git.busybox.net/buildroot
          REPO_BRANCH: 2021.11
        run: |
          df -hT $PWD
          git config --global advice.detachedHead false
          git clone --recurse-submodules --branch $REPO_BRANCH $REPO_URL
          cd /workdir/buildroot
          git checkout $REPO_BRANCH
          git pull origin $REPO_BRANCH

          ln -sf /workdir/buildroot $GITHUB_WORKSPACE/buildroot
          sudo apt-get -qq install sed make binutils gcc g++ bash patch bzip2 perl tar cpio unzip rsync wget libncurses-dev 
      
      - name: build
        run: |
          cd $GITHUB_WORKSPACE/buildroot
          make O="$ER6POUT" list-defconfigs


########################################Merge all workflows################################################
  mergeall:
    needs: [er6P, raspberry3B]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          submodules: true
      
      - name: create release folder
        run: |
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir $GITHUB_WORKSPACE/$RELEDIR
          sudo chown $USER:$GROUPS $GITHUB_WORKSPACE/$RELEDIR

      - uses: actions/download-artifact@v3
        with:
          name: raspi3b-toolchain
          path: ${{ github.workspace }}/${{ env.RELEDIR }}

      - name: generate release tag
        id: reltags
        if: (!cancelled())
        run: |
          echo -e "release_tag=$(date +"%Y.%m.%d-%H%M%S")" >> $GITHUB_OUTPUT
          touch release.txt
          echo -e "stat=success" >> $GITHUB_OUTPUT

      - name: push to release
        uses: softprops/action-gh-release@v1
        if: steps.reltags.outputs.stat == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.reltags.outputs.release_tag }}
          body_path: release.txt
          files: ${{ github.workspace }}/${{ env.RELEDIR }}/*
